# Generated by Django 5.1.1 on 2024-09-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E_learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=500)),
                ('notes', models.FileField(default=None, max_length=250, null=True, upload_to='media')),
                ('thumnail', models.ImageField(default=0, upload_to='media')),
            ],
        ),
    ]
