# Generated by Django 5.1.1 on 2024-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(default=None)),
                ('certificate', models.ImageField(default=0, upload_to='media')),
                ('thumnail', models.ImageField(default=0, upload_to='media')),
                ('fees', models.IntegerField(default=None)),
            ],
        ),
    ]
