# Generated by Django 5.1.1 on 2024-09-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default=None, max_length=100, null=True)),
                ('course_name', models.ForeignKey(db_column='course_name', on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
    ]
