# Generated by Django 5.1.1 on 2024-09-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_skills_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='skills_topic',
        ),
    ]
