# Generated by Django 5.1.1 on 2024-09-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_skills_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_skills',
            name='chapter',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
