# Generated by Django 5.1.1 on 2024-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_e_learning_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video1',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
